# Generated by Django 4.2.26 on 2025-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
