# Generated by Django 4.2.26 on 2025-11-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapp', '0002_accesscode_token_alter_accesscode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
